services:
  - type: web
    name: qremenu
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn emenu.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.10"
