# Generated by Django 5.0.6 on 2024-10-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notsubmitteditem',
            old_name='table_number',
            new_name='tableNumber',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='table_number',
            new_name='tableNumber',
        ),
        migrations.RenameField(
            model_name='submitteditem',
            old_name='table_number',
            new_name='tableNumber',
        ),
    ]
