# Generated by Django 5.2.5 on 2026-08-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_rename_table_number_notsubmitteditem_tablenumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant_id',
            field=models.CharField(default='R001', max_length=50),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant_id',
            field=models.CharField(default='R001', max_length=50),
        ),
        migrations.AddField(
            model_name='notsubmitteditem',
            name='restaurant_id',
            field=models.CharField(default='R001', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurant_id',
            field=models.CharField(default='R001', max_length=50),
        ),
        migrations.AddField(
            model_name='submitteditem',
            name='payment_method',
            field=models.CharField(choices=[('none', 'None'), ('cash', 'Cash'), ('upi', 'Hotel UPI QR')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='submitteditem',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='submitteditem',
            name='restaurant_id',
            field=models.CharField(default='R001', max_length=50),
        ),
        migrations.AlterField(
            model_name='submitteditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending / New'), ('confirmed', 'Preparing'), ('ready', 'Ready to Serve'), ('served', 'Served'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.CharField(default='R001', max_length=50)),
                ('role', models.CharField(choices=[('KITCHEN', 'Kitchen Staff'), ('WAITER', 'Staff / Waiter'), ('RESTAURANT_ADMIN', 'Restaurant Admin'), ('SUPER_ADMIN', 'Super Admin')], default='WAITER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
