# Generated by Django 5.2.5 on 2026-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitteditem',
            name='order_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
